sudo: false
dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- python setup.py install
script:
- python setup.py test
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy:
- git config --local user.name "Ilya Chichak"
- git config --local user.email "ilyachch@gmail.com"
- export TRAVIS_TAG=$(cat VERSION)
- git tag $TRAVIS_TAG
deploy:
  provider: pypi
  user: ilyachch
  password:
    secure: vWlr6bANondjULFZGqE1LZ0w/HM+72OIsTWPcvigyimtPiWwwvwVn6lDDhUKQr32AywF7BivIsCcUjtTqNuCTWN3xJx2InaoS9rlYljdqkHWxHqrkmn59Wuhx7FRQ/QeG6MLvt2KqKu8How/o6mhadhwwj9fyvMh7mqj/o2mZqfO/AbU5aN0HUGvD3MIG4XXUD2h8WHoWv8YfPDceCBz3XwiB+MtK/Hzi94jVyjr0RFj9S+qDv0NnPvyu9Lp1//Jb526e/OrUAKHYl6zF2q6jhHRTQ2P0OmizUEoALlKyQfHDMwMcDeyMJh5ts6/MziKitZydYnQwo84PmynfYth9uEHhXSEkV9zsHrkpLO+RejUH0iVo59yp9Ta2HxT9XfFVC0nF4XqiUmFK+oFeAJoqScTZ4qwEXxlV8HB2IyU1S01auae2d4udxldYtC1aPlHGDPvesV1D/QW7Gm+LrkTKZQfv3OWFMr3ghMcirzorSR+2+o9mpdrKWZFMo2CPqQTP4bUyrZfYEZilN4k1xhRKFhMJcAcGaNFYbyFsm7LEtDZ4kYbLSlBYb7etrzTMh9Jst4Sm+8L8Xf8m4+LBF4i1HwQhvowTbaEWUI1R9sVQTN1DqURSsQv2hee1Nz+7u7YogWqvErA290uBqiGCT3jKEIlDOcfeJ8eblLcQ+li6po=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_existing: true
  on:
    repo: ilyachch/md_docs-trans-app
    branch: master
    python: '3.6'
