sudo: false
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
install:
  - python setup.py install
script:
  - python setup.py test
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy:
  - if ! [[ $TRAVIS_TAG ]]; then
    export TRAVIS_TAG=$(cat VERSION) &&
    git config --local user.name "$USER_NAME" &&
    git config --local user.email "$USER_EMAIL" &&
    git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT";
    fi
deploy:
  - provider: pypi
    user: ilyachch
    password:
      secure: vWlr6bANondjULFZGqE1LZ0w/HM+72OIsTWPcvigyimtPiWwwvwVn6lDDhUKQr32AywF7BivIsCcUjtTqNuCTWN3xJx2InaoS9rlYljdqkHWxHqrkmn59Wuhx7FRQ/QeG6MLvt2KqKu8How/o6mhadhwwj9fyvMh7mqj/o2mZqfO/AbU5aN0HUGvD3MIG4XXUD2h8WHoWv8YfPDceCBz3XwiB+MtK/Hzi94jVyjr0RFj9S+qDv0NnPvyu9Lp1//Jb526e/OrUAKHYl6zF2q6jhHRTQ2P0OmizUEoALlKyQfHDMwMcDeyMJh5ts6/MziKitZydYnQwo84PmynfYth9uEHhXSEkV9zsHrkpLO+RejUH0iVo59yp9Ta2HxT9XfFVC0nF4XqiUmFK+oFeAJoqScTZ4qwEXxlV8HB2IyU1S01auae2d4udxldYtC1aPlHGDPvesV1D/QW7Gm+LrkTKZQfv3OWFMr3ghMcirzorSR+2+o9mpdrKWZFMo2CPqQTP4bUyrZfYEZilN4k1xhRKFhMJcAcGaNFYbyFsm7LEtDZ4kYbLSlBYb7etrzTMh9Jst4Sm+8L8Xf8m4+LBF4i1HwQhvowTbaEWUI1R9sVQTN1DqURSsQv2hee1Nz+7u7YogWqvErA290uBqiGCT3jKEIlDOcfeJ8eblLcQ+li6po=
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_existing: true
    on:
      repo: ilyachch/md_docs-trans-app
      branch: master
      python: '3.6'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: mLbq3UU3SGjc0LDAnMnljbB7BxPBEylIkPoCuuYbN0EnwAwbyA4biTbTl91qINkQbUTMNJus0RuKXdM2I7irH/K559Gzd+E7lbu1olCc5MH0txPLFBi3bAiqTG64KkLxl9dmo2Ko0GZP8GZBWh5K5J1O69A2PEv7YILZO9MxeYb51yUQNcnAalhyGPdsDkOYB4r0HRLWoYQjdhM1E2iL5wMf7sdaDTpbnOLXUWrElRugc3kxuvMUbfzteMukJA/IbF6WzPMzX3mZAnQySGJZrBau4kOH8InT/aMy9F9+TuJsWVrfZ6J09qWeix/TNVqBC2O+Ow1NJLW0KI17KM/XODCf5skOu7hEoz16WUKC2xEwIkQmHgOhRJ3s1/t3+SIYyCwkJwtwN2R1TcCG07U5Z8PC9FOvjHCqOQrioNJAXIqUlJBb0b+yQTM/m9ov/GooNySPhvoXujsINSOe3GTWVGzEB13VjCeG0f65sO1QqDT4hCNQuqi0uyckava7hTnvnhbjH1w/OBeyvSh3azZMbaxZenR+UO1OV3jZ1VC66Z4yPrZhF+fGMTgzCc8ubA/XrSu+kPhZZGKNQSMLoh4z8H1zU7noCCkr+bY29eXJFRSvAxP7Y0CWq/J6TgDFKGfd+p6XeO/yBrsegOqyvrLKtrNuqwh6wop/WT21NNDTEUg=
    file:
      - dist/*.whl
      - dist/*.tar.gz
    on:
      repo: ilyachch/md_docs-trans-app
      branch: master
      python: '3.6'
