sudo: false
dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- python setup.py install
script:
- python setup.py test
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy:
- git config --local user.name "Ilya Chichak"
- git config --local user.email "ilyachch@gmail.com"
- export TRAVIS_TAG=$(cat VERSION)
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: wiRboxT8sh2pfVgL4AlebUrK9sZ3vzQmooDVGANeHZakV7Oo2YTISjD7E/q0ZCjHU/Q5AUR3oEWtYLyw168VQCpUzfhH5yNR+8T7NaToIdb/qmKegjpvAYsKlQwYqDS3cGYWdbYZSCUg6X1tEg1S6ntWd55t85cv9gtuokSGtndHPTfzBMqLmWJYDy4o0DFIHiazM6hInnSV4QDkakXrapbiEj7ytzhjKY2kPSMS5vrfDZvpBTiS5QJzNfBMDiiyWyQz5WDaJYMjsTvwsH1clhaYuzIYuYIbTN3UJeG7ClhpQRZAK8a4+Qic8JJXHFkajGWGUV8ywhsEjYa76qch9PsN3EQRejTmJy9u+YD9XHWTVIJ89DoMHnbwvsPJcKqOvUoj8lbnND2PAGQjMPGKAQYTOMuTENH/PvXw8NXpPOdGlzT6BDo8oO6mqdL5JjJ+BoriWDuye0q5dogyL/OmJ3XWPIy76j+45cnct9KWRAG0qQkTsoeQOnMSA0S+ATn8z55XyIOLjY5KLHNgJbTOd2pG0dTKBVGoq+eFdLXoIRGFeeRS32wyOtbkGnpa9k+vGxG3D7oTPTx1rmx5jDBF2Qr9kDpJV/8m4ATVvFC5ClgnXBn/p/8S2sBFzuF+/mvdmEqcX1BZdMEQvB5uA7S0si1HPiGmalWZCPJpLrN45Jk=
  file:
    - dist/*.whl
    - dist/*.tar.gz
  on:
    repo: ilyachch/md_docs-trans-app
