name: Linting

on:
  pull_request:
    branches: master
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        validation-command: [ "check_mypy", "check_isort", "check_flake8" ]

    steps:
      - name: Getting code
        uses: actions/checkout@master
      - name: Getting Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Installing dependencies
        run: poetry install
      - name: Running types checks
        run: make ${{ matrix.validation-command }}
