name: Pull request checking
on:
  pull_request:
    branches: master
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
jobs:
  lint:
    uses: ./.github/workflows/linting.yml
    name: Linting
    with:
      python-version: "3.10"
      commands: ${{ toJSON([ "make check_mypy", "make check_isort", "make check_flake8" ]) }}
      system: "ubuntu-20.04"
  test:
    uses: ./.github/workflows/testing.yml
    name: Testing
  validate_version:
    uses: ./.github/workflows/validate_version.yml
    name: Validate Version
    needs: [lint, test]
