name: Pull request checking
on:
  pull_request:
    branches: master
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
jobs:
  lint:
    uses: ./.github/workflows/linting.yml
    strategy:
      fail-fast: false
      matrix:
        validation-command: [ "make check_mypy", "make check_isort", "make check_flake8" ]
        system: [ "ubuntu-20.04", "ubuntu-22.04" ]
        python-version: [ "3.10", "3.11" ]
    name: Linting
    with:
      python-version: ${{ matrix.python-version }}
      command: ${{ matrix.validation-command }}
      system: ${{ matrix.system }}
  test:
    uses: ./.github/workflows/testing.yml
    name: Testing
    strategy:
      fail-fast: false
      matrix:
        system: [ "ubuntu-20.04", "ubuntu-22.04" ]
        python-version: [ "3.10", "3.11" ]
  validate_version:
    uses: ./.github/workflows/validate_version.yml
    name: Validate Version
    needs: [lint, test]
