name: Tests
on:
  workflow_call:
    inputs:
      system:
        description: 'System to run on'
        required: false
        type: string
        default: ubuntu-20.04
      command:
        description: 'Command to run'
        required: false
        type: string
        default: "make tests"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.python-version }}-${{ github.event.inputs.system }}-${{ github.event.inputs.command }}
  cancel-in-progress: true
jobs:
  test_pr:
    name: Tests
    runs-on: ${{ inputs.system }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - name: Getting code
        uses: actions/checkout@v3
      - name: Getting Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Load cached poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry-${{ steps.setup-python.outputs.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}-${{ steps.setup-python.outputs.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Installing dependencies
        run: poetry install
      - name: Running tests
        run: ${{ inputs.command }}
