name: Validate Version change

on:
  pull_request:
    branches: master
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  validate_version:
    name: Validate Version
    runs-on: ubuntu-20.04
    steps:
      - name: Getting code
        uses: actions/checkout@master
      - name: Getting Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
      - name: Check version is changed
        run: |
          if ! git diff master HEAD pyproject.toml | grep -E "^[-+]version"; then
            echo "Version is not changed"
            exit 1
          fi
      - name: Get new version
        id: get_new_version
        run: |
          echo "::set-output name=version::$(git diff master HEAD pyproject.toml | grep -E "^\+version" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+")"
      - name: Get old version
        id: get_old_version
        run: |
          echo "::set-output name=version::$(git diff master HEAD pyproject.toml | grep -E "^\+version" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+")"
      - name: Check version format
        run: |
          if ! echo "${{ steps.get_new_version.outputs.version }}" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$"; then
            echo "Version is not in format X.Y.Z"
            exit 1
          fi
      - name: Check new version is greater than old version
        run: |
          if [[ ${{ steps.get_new_version.outputs.version }} <= ${{ steps.get_old_version.outputs.version }} ]]; then
            echo "New version is not greater than old version"
            exit 1
          fi
